version: '3.1'

services:

  db:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tskon1_asuka_frm
      MYSQL_USER: tskon1_asuka_frm
      MYSQL_PASSWORD: q1w2Q!W@
#    volumes:
#      - $PWD/databaseBackup:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 9090:8080
