version: '3.1'

services:

  db:
    build: ./db
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: asuka_events
    volumes:
      - $PWD/databaseBackup:/var/lib/mysql

  phpmyadmin:
    build: ./phpMyAdmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - 8080:80
    volumes:
      - /sessions
